# random_seed: 42

# --- File Paths ---
paths:
  input_docs: "data/input/documents.jsonl"
  evaluation_data: "data/raw/tsar2025_trialdata.jsonl"
  prompts_dir: "prompts/"
  prompt_assets_dir: "prompt_assets/"
  results_dir: "results/"
  scored_references: "data/references_with_scores.jsonl"
  source_difficulty_data: "data/source_with_difficulty.jsonl"

# --- Model Definitions ---
# Define the models you can use.
models:
  gpt-4o:
    type: "gpt"
    api_model_name: "gpt-4o"
    temperature: 1.0
  o1:
    type: "gpt"
    api_model_name: "o1-2024-12-17"
    temperature: 1.0
  o3:
    type: "gpt"
    api_model_name: "o3-2025-04-16"
    temperature: 1.0
  
  gpt-5:
    type: "gpt"
    api_model_name: "gpt-5-2025-08-07"
    temperature: 1.0
  
  claude-3-7-sonnet:
    type: "claude"
    api_model_name: "arn:aws:bedrock:ap-southeast-2:340752822738:inference-profile/apac.anthropic.claude-3-7-sonnet-20250219-v1:0"
    temperature: 1.0
  claude-4-sonnet:
    type: "claude"
    api_model_name: "arn:aws:bedrock:ap-southeast-2:340752822738:inference-profile/apac.anthropic.claude-sonnet-4-20250514-v1:0"
    temperature: 1.0
  
  gemma-3-4b-it:
    type: "gemma"
    api_model_name: "google/gemma-3-4b-it"
    temperature: 1.0

# --- Pipelines ---
pipelines:
  # - name: "gemma_2_9b_cot" # The pipeline gets the old experiment name
  #   steps:
  #     - step_name: "simplify" # Give the single step a simple name
  #       model: "gemma-2-9b-it"
  #       prompt_template: "chain_of_thought.txt"
  #       sample_size: 3

  # - name: "gpt4o_contrastive_confidence"
  #   steps:
  #     - step_name: "simplify_contrastive"
  #       model: "gpt-4o"
  #       prompt_template: "contrastive_few_shot.txt"
  #       contrastive:
  #         num_examples: 2
  #       few_shot_selection: "confidence"
  #       sample_size: 5

  - name: "gpt5_chinese_spanish"
    steps:
      - step_name: "translate"
        model: "gpt-5"
        prompt_template: "translate.txt"

      - step_name: "translate_and_simplify"
        model: "gpt-5"
        prompt_template: "simplify_from_translation.txt"
  
  - name: "o1_chinese_spanish"
    steps:
      - step_name: "translate"
        model: "o1"
        prompt_template: "translate.txt"

      - step_name: "translate_and_simplify"
        model: "o1"
        prompt_template: "simplify_from_translation.txt"
  
  - name: "claude_chinese_spanish"
    steps:
      - step_name: "translate"
        model: "claude-4-sonnet"
        prompt_template: "translate.txt"

      - step_name: "translate_and_simplify"
        model: "claude-4-sonnet"
        prompt_template: "simplify_from_translation.txt"
  
  - name: "gemma_chinese_spanish"
    steps:
      - step_name: "translate"
        model: "gemma-3-4b-it"
        prompt_template: "translate.txt"

      - step_name: "translate_and_simplify"
        model: "gemma-3-4b-it"
        prompt_template: "simplify_from_translation.txt"
  
